---
## we should install plugin by using this command   =>   ansible-galaxy collection install amazon.aws
plugin: aws_ec2
regions:
- "us-east-2"
keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
filters:
  instance-state-name: running
  tag:Name:
    - jenkins_server
compose:
  ansible_host: public_ip_address
